### ISSUE TITLE
missing ivector extractor from prebuilt model archive

### ISSUE THREAD

**Issue by olix20** [tudarmstadt-lt/kaldi-tuda-de#16]
Hi and thanks for sharing your model. 

I test your model but it seems that the ivector extractor is missing from the archive in this adress:
http://ltdata1.informatik.uni-hamburg.de/kaldi_tuda_de/tdnn_chain_cleaned_tuda_swc_voc126k.tar.bz2

**Comment by bmilde** [comment]
Thanks for pointing this out! I've added the extractor to the archive. It's also available as a separate download: http://ltdata1.informatik.uni-hamburg.de/kaldi_tuda_de/tdnn_chain_cleaned_tuda_swc_voc126k_ivector_extractor.tar.bz2

Let me know if you get the model running successfully now.

**Comment by olix20** [comment]
Thanks I managed to run it!
