### ISSUE TITLE
Corpus for LM

### ISSUE THREAD

**Issue by svenha** [tudarmstadt-lt/kaldi-tuda-de#2]
I found this file: all_corpora_filtered_maryfied.txt.gz .
Does a version before applying "mary" (and/or filtering) exist somewhere?

**Comment by bmilde** [comment]
You can now find the non-filtered and non-maryfied file here: http://dialogplus.lt.informatik.tu-darmstadt.de/downloads/speechdata/German_sentences_8mil.tar.bz2
