### ISSUE TITLE
Error when I try to run run.sh However I can't find any variable called sequitur_g2p in run.sh,

### ISSUE THREAD

**Issue by maggieezzat** [tudarmstadt-lt/kaldi-tuda-de#21]
Could not find g2p.py
Please edit run.sh and point sequitur_g2p to the g2p.py python script of your Sequitur G2P installation.
Sequitur G2P can be downloaded from https://www-i6.informatik.rwth-aachen.de/web/Software/g2p.html
E.g. wget https://www-i6.informatik.rwth-aachen.de/web/Software/g2p-r1668-r3.tar.gz

**Comment by maggieezzat** [comment]
I also created a file called sequitur_g2p and called in it the g2p.py script but I get the same error

**Comment by maggieezzat** [comment]
sequitur_g2p variable is in cmd.sh and not run.sh, please correct the readme

**Comment by AASHISHAG** [comment]
@maggieezzat : were you able to successfully run the entire script? If yes, could you please share the results? I still face lot of errors.

**Comment by maggieezzat** [comment]
What errors do you get? You can share the error logs
