### ISSUE TITLE
m_ailab speech dataset's website

### ISSUE THREAD

**Issue by iezhanqingran** [tudarmstadt-lt/kaldi-tuda-de#24]
I couldn't open the m_ailab's website, could you please check it?
Thanks

**Comment by svenha** [comment]
The website disappeared some months ago. There is a mirror at https://www.caito.de/2019/01/the-m-ailabs-speech-dataset/

**Comment by iezhanqingran** [comment]
> The website disappeared some months ago. There is a mirror at https://www.caito.de/2019/01/the-m-ailabs-speech-dataset/

Thanks! Got it
