### ISSUE TITLE
empty wav on m_ailab dataset

### ISSUE THREAD

**Issue by iezhanqingran** [tudarmstadt-lt/kaldi-tuda-de#25]
when I run this recipe, I found that there are some wavs are empty like:data/wav/german-speechdata-package-v2/train/2014-03-24-13-39-24_Kinect-RAW.wav, so there are some errors when get the duration of the wav files, and I removed it, but could you please still check it?
Thanks,

**Comment by jborbik** [comment]
I noticed this as well. Have a look on my PR (https://github.com/uhh-lt/kaldi-tuda-de/pull/23) where I added automatic removal of the files, for which any of the mic recording is empty. I fixed also other errors for training.

**Comment by iezhanqingran** [comment]
thanks!

**Comment by iezhanqingran** [comment]
Hi,
Did you try chain model using uncleaned data?
I still found a lot of wavs which has no duration in header, like: 347f5bd2-0ee7-4f47-a465-82b32752e4cb_2014-08-05-11-08-34_a.
Thanks.

**Comment by jborbik** [comment]
I only added to the list the files, which were breaking the training process. If there are more files which are empty and you could list them, that would be very nice. 

EDIT: I have added new files to delete, please check if you see some which are not listed right now.

**Comment by bmilde** [comment]
@Jendker Thank you again for your pull request to address this!
@iezhanqingran Are there still any other empty files we should add to the list of files to omit?

**Comment by iezhanqingran** [comment]
Yes, I think there are still some wav files has bad stand header in m_ailab dataset. I'm on holiday now, I'll check it next week. @bmilde

**Comment by iezhanqingran** [comment]
I think the wav files in the list are the all empty files.
Thanks
