### ISSUE TITLE
How to run/compile MARY 5.1.1?

### ISSUE THREAD

**Issue by AASHISHAG** [tudarmstadt-lt/kaldi-tuda-de#26]
The documentation on running MARY 5.1.1 version is missing on the official page. Could you please point out, how to run it?

**Comment by bmilde** [comment]
Hi,

there should be some information in the README of the old s5 recipe.

Note that MARY is not needed to run the recent s5_r2 recipes, it was previously used to generate phonetic entries for OOV words. We now use Sequitur G2P for that (it's also better).
