### ISSUE TITLE
SWC Alignments

### ISSUE THREAD

**Issue by maggieezzat** [tudarmstadt-lt/kaldi-tuda-de#28]
I used the segment file for SWC found in http://speech.tools/kaldi_tuda_de/swc_train_v2.tar.gz to segment the wav files for my ASR. However when checking the data, the audio alignments were very faulty.  Did you use the data like that or some correction was performed to make the alignments more accurate? Would it harm the model if I used these faulty segmentations?

**Comment by akoehn** [comment]
Can you give some examples for "very faulty"?
We did some analysis of the alignment quality in the [SWC journal paper](https://doi.org/10.1007/s10579-017-9410-y) ([pre-print](https://arne.chark.eu/static/spoken-wp-corpus-collection.pdf)) and while not everything is aligned, the words that are aligned seemed to be okay.

We used the segmentation as-is for [the German kaldi model](https://ieeexplore.ieee.org/document/8578033) ([arXiv pre-print](https://arxiv.org/abs/1807.10311)) and mismatching alignments are filtered out automatically, therefore there should be little harm in simply using everything.

**Comment by moustafamariam** [comment]
How are the mismatching alignments filtered out automatically?

**Comment by bmilde** [comment]
As SWC is an automatically aligned resource of found speech, some
transcription errors are expected. As part of the run script, 
https://github.com/uhh-lt/kaldi-tuda-de/blob/master/s5_r2/local/run_cleanup_segmentation.sh
is
called. It decodes the training set and discards utterances that don't
match well enough. The parameters and what "well enough" means can also be
tuned, but we just use the defaults. If I remember correctly about 10% of
the data is discarded at this step. The GMM-HMM models that are trained on
the 'dirty' data before this step also gracefully handle garbage utterances
that contain something completely mismatched, you see this in the output
with the "fail rate". The fail rate goes down significantly for the GMM-HMM
that is trained on the automatically cleaned data.

As long as the majority of the utterances are correct, some transcription
errors are not a problem at all. More data is better, as the WER numbers
show, even if you add 'dirty' data.
