### ISSUE TITLE
The amount of the data

### ISSUE THREAD

**Issue by iezhanqingran** [tudarmstadt-lt/kaldi-tuda-de#29]
Hi,
from your readme, the data is 600+ hours, but after I run the recipe, there are only 400h data for chain model training, so someone can give me some suggestions? 
Thanks

**Comment by bmilde** [comment]
Can you check if all the datasets (german tuda, SWC, m-ailabs data) are correctly downloaded an build?

**Comment by bmilde** [comment]
Also, unfortunatly, the scripts will silently fail on tuda if lxml and bs4 is not installed. So be sure to do:

pip3 install beautifulsoup4 lxml

before you run the scripts.

**Comment by bmilde** [comment]
complete training data should be about 1000h with newest scripts now
