### ISSUE TITLE
Rerunning kaldi-tuda-de on a single wav file

### ISSUE THREAD

**Issue by svenha** [tudarmstadt-lt/kaldi-tuda-de#3]
I am tracking an error in my setup of kaldi. How can I rerun kaldi with a given setting (e.g. the one corresponding to exp/sgmm_5a_mmi_b0.1/decode4/wer_13) on a single wav file? Thanks for your time and effort!

**Comment by bmilde** [comment]
Hi, that would also interest me. Did you figure it out? If not, it would probably also be a good idea to ask this on the Kaldi mailing list.

**Comment by svenha** [comment]
Hi. No, I have no solution yet. I did'n ask on the Kaldi mailing list, because it seemed to be too trivial :-) But now I will.

**Comment by svenha** [comment]
The solution is simple: one should modify the file feats.scp .

**Comment by bmilde** [comment]
Related to this: I've added the file decode.sh to kaldi-tuda-de
It shows how to use the sgmm model in batch mode to generate automatic transcripts for new data.

Can you elaborate on what you had to change in feats.scp? Thanks.

**Comment by svenha** [comment]
Thanks. decode.sh works for me!

(The file feats.scp was only relevant because I wanted to rerun the trained model on a selected train file; unusual use case.)

**Comment by bmilde** [comment]
Ah, ok, I then misunderstood you at first. Anyway, I think having a decode example script is a good idea. Glad that it worked for you!
