### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by clu-pei-dae** [tudarmstadt-lt/kaldi-tuda-de#31]
After ~3 days of training the script crashed because of missing parantheses in `choose_utt_to_combine.py`. The last log was

```
...
utils/validate_data_dir.sh: Successfully validated data-directory data/train_cleaned_sp_hires
utils/data/get_utt2dur.sh: data/train_cleaned_sp_hires/utt2dur already exists with the expected length.  We won't recompute it.
choose_utts_to_combine.py: combined 1081479 utterances to 1020406 utterances while respecting speaker boundaries, and then to 1020308 utterances with merging across speaker boundaries.
  File "<string>", line 25
    print uniq, uniq2orig_uniq[uniq]
             ^
SyntaxError: Missing parentheses in call to 'print'
```

Are the scripts supposed to be ran with python 2 rather then 3?

**Comment by svenha** [comment]
The file `egs/wsj/s5/utils/data/internal/choose_utts_to_combine.py` is for Python 2. I produced a successful run (stopping at the GPU step - only because I forgot CUDA support in Kaldi :-) )  with python being `Python 2.7.16`.

**Comment by bmilde** [comment]
Unfortunately many of Kaldis internal Python scripts (and the ones in wsj/s5/utils) are Python 2 only. Kaldi assumes that calling python invokes python2 and the kaldi-tuda-de scripts always  explicitly call python3 to get a version 3 interpreter. This is also standard on e.g. Ubuntu.
