### ISSUE TITLE
Add Mozilla Common Voice corpus

### ISSUE THREAD

**Issue by codeforequity-at** [tudarmstadt-lt/kaldi-tuda-de#34]
Hi,
Is there a special reason why the Mozilla common voice is not part of this recipe ? Maybe licensing issues ?
If I prepared a pull request adding Mozilla common voice corpus to this recipe, would you accept it ?

**Comment by bmilde** [comment]
Hi!

Ive already prepared most of necessary scripts, havent pushed it yet. Its
comming very soon! But if you want to help me test it, I'd welcome that.
Let me know,

Best,
Benjamin

Botium <notifications@github.com> schrieb am Sa., 4. Jan. 2020, 18:24:

**Comment by codeforequity-at** [comment]
Absolutely. I suggest pushing to a feature branch so I can checkout to my machine.

On another note, I am currently preparing a Dockerfile to make this recipe work without having to install all the requirements manually. Maybe this would be a good contribution.

**Comment by bmilde** [comment]
Nearly ready! I'm currently running into problem similar to https://groups.google.com/forum/#!topic/kaldi-help/BxvNZuxTgz0 but that seems to be an OpenBLAS bug. I'll push the added code once the TDNN training runs.

**Comment by bmilde** [comment]
Hi @codeforequity-at!

I've added common voice to the training data (1000h in total now!). We also have a new LM based on https://github.com/bmilde/german-asr-lm-tools 

Have you had success with the Dockerfile?
