### ISSUE TITLE
tree for pretrained chain model 

### ISSUE THREAD

**Issue by linkin627** [tudarmstadt-lt/kaldi-tuda-de#39]
Hi I'm trying to create a new `HCLG.fst` with my own language model, I was wondering if you could upload `tree` for `de_400k_nnet3chain_tdnn1f_2048_sp_bi`? Thanks!

**Comment by RicWg** [comment]
Great question, can we have the data/lang folder for the final graph of the voc683k model, too?

**Comment by bmilde** [comment]
The tree is now part of the new pretrained model packages (900k model) and the data lang folders are now available as a separate download at http://ltdata1.informatik.uni-hamburg.de/kaldi_tuda_de/de_900k_lang_dirs.tar.bz2
