### ISSUE TITLE
ERROR: SymbolTable::ReadText: Can't open file data/lang_test/words.txt

### ISSUE THREAD

**Issue by bakuzen** [tudarmstadt-lt/kaldi-tuda-de#4]
I downloaded the corpus separately and put the data into the proper folder. I then ran ./run.sh which worked for a while (building LMs and doing data prep, it appeared) until it stopped on the above error. It is probably the case that the root cause came earlier, as the above-mentioned file doesn't exist at all. Below is the output from the script from program invocation all the way until the error. 

[kaldierror.txt](https://github.com/tudarmstadt-lt/kaldi-tuda-de/files/60948/kaldierror.txt)

**Comment by bmilde** [comment]
Yes, the error came earlier. The data preparation script didn't start at all: "ImportError: No module named bs4"
You need the beautifulsoup package installed in order to run it:

```
pip install beautifulsoup4
```

That should fix it.

**Comment by bakuzen** [comment]
That indeed fixed it. Sorry I didn't notice that!
