### ISSUE TITLE
Kaldi data preprocessing

### ISSUE THREAD

**Issue by Tortoise17** [tudarmstadt-lt/kaldi-tuda-de#40]
Dear Friends. 

I am trying to preprocess the kaldi data SWC

but, I failed several times. 
I have error 
Invalid data set of type kaldi: files wav.scp text not found at data/swc

Can you guide me how to process / preprocess it to get those required files? any script available?

**Comment by bmilde** [comment]
This sounds like you (or run.sh) didn't download http://ltdata1.informatik.uni-hamburg.de/kaldi_tuda_de//swc_train_v2.tar.gz
 
This tar archive contains the files wav.scp text etc. that are necessary for Kaldi.
