### ISSUE TITLE
Issues executing run.sh

### ISSUE THREAD

**Issue by prvit** [tudarmstadt-lt/kaldi-tuda-de#44]
Greetings,

I've installed kaldi using their `INSTALL` in `/tools` and `/src`.
I was using make with `USE_THREAD=0`  as described and correctly installed OpenBLAS to be used from a shared directory.
I also successfully installed Sequitur G2P and all other requirements.
First, I had an error that 'spacy' module not found after the first run of `./run.sh`.
I installed it using `pip3 install -U spacy` and then downloaded de model by `python3 -m spacy download de`.
But now I am getting the following error :

```console
+ python3 local/export_lexicon.py -f data/local/combined.dict -o data/local/dict_std_big_v5/_lexiconp.txt
Load  data/local/combined.dict
Succesfully opened pickle file, now exporting to: data/local/dict_std_big_v5/_lexiconp.txt
Warning!: No % entry found! Will add <UNK> -> usb mapping manually.
Warning!: No <Lachen> entry found! Will add <Lachen> -> lau mapping manually.
+ g2p_model=data/local/g2p_std_big_v5/de_g2p_model
+ final_g2p_model=data/local/g2p_std_big_v5/de_g2p_model-6
+ mkdir -p data/local/g2p_std_big_v5/
+ '[' 0 -le 5 ']'
+ train_file=data/local/g2p_std_big_v5/lexicon.txt
+ cut '-d ' -f 1,3- data/local/dict_std_big_v5/_lexiconp.txt
+ cut '-d ' -f 1 data/local/dict_std_big_v5/_lexiconp.txt
+ '[' '!' -f data/local/g2p_std_big_v5/de_g2p_model-6 ']'
+ mkdir -p data/local/g2p_std_big_v5/
+ /usr/local/bin/g2p.py -e utf8 --train data/local/g2p_std_big_v5/lexicon.txt --devel 3% --write-model data/local/g2p_std_big_v5/de_g2p_model-1
  File "/usr/local/bin/g2p.py", line 184
    except translator.TranslationFailure, exc:
                                        ^
SyntaxError: invalid syntax
```

My google search didn't help me to find out how to fix the problem. I tried to reinstall gg2p but it didn't help.
Could you help me with this one, please?
I can provide full console output if needed.

**Comment by prvit** [comment]
Guys, any ideas on how to fix an issue above?

**Comment by svenha** [comment]
Could this be a python2 vs python3 problem? Check the first line of your `g2p.py`.

**Comment by prvit** [comment]
It was an issue with ```g2p.py``` . Reinstalled it once again and an error was gone.
