### ISSUE TITLE
Installation check and better error handling

### ISSUE THREAD

**Issue by bmilde** [tudarmstadt-lt/kaldi-tuda-de#5]
Currently, the run.sh scripts runs through even though errors occur in the data prepartions scripts. This could easily be fixed with appropriate exit checks in run.sh, so that they stop at the correct point.
Also it would be a good idea to check the installation with an additional script, e.g. that Kaldi, Mary and additional Python modules are correctly installed.

**Comment by svenha** [comment]
A related idea would be to publish a file with md5sums (or similar) of files generated during the run.sh run. So, one can easily check (by hand) where possible problems started ... Of course, in a second step this can be also done by the script automatically. But let's proceed step by step :-)

**Comment by bmilde** [comment]
I've added a pipefail command to run.sh, so that the shell aborts on the first error. This makes it much easier to see where things fail.

For certain commands that are allowed to fail, a "| true" needs to be appended though.
