### ISSUE TITLE
local/run_ivector_common.sh: expected file data/train_cleaned/feats.scp to exist

### ISSUE THREAD

**Issue by Tortoise17** [tudarmstadt-lt/kaldi-tuda-de#51]
After downloading the data, when I try to use the cuda with kaldi. it failed. 
It throws error 
local/run_ivector_common.sh: expected file data/train_cleaned/feats.scp to exist

while. 

s5_r2/run.sh while running on cpu only works without any error. 

Can you guide the proper run for cuda utilization which also after prepares the data makes all process on cuda for kaldi?
Your kind help is highly appreciated.

**Comment by bmilde** [comment]
Hi, if data/train_cleaned/feats.scp isn't there (what the error says) then
something went wrong in run.sh. Has nothing to do with cuda.

You can run ./show_results.sh to see if you have successfully decoded
something with the bootstrap models.

**Comment by Tortoise17** [comment]
Oh it means first I have to 
$s5_r2/run.sh let it complete and then train on cuda as next step? with 
$s5_r2/local/run_tdnn1f.sh ?

because ./show_results.sh has nothing 

Please guide for steps to follow. I am very new with kaldi.

**Comment by Tortoise17** [comment]
also guide me bit more. 
run.sh is running. I want to ask as guess how much time I should expect to run.sh running for your this dataset? because I am running it around 5 hrs and still it is running on 8 cores at the moment.

**Comment by bmilde** [comment]
It takes about 1 week with 28 cores

**Comment by Tortoise17** [comment]
ok and after 1 week, cuda time for the training?

**Comment by bmilde** [comment]
Yes you need to bootstrap gmm-hmm models to align the speech data for
tdnn-hmm , like stated in our paper
Http://edoc.sub.uni-hamburg.de/informatik/volltexte/2018/243/

I suggest to try some Kaldi tutorials first to get a feeling for Kaldi and
its shell scripts

**Comment by Tortoise17** [comment]
thank you .. !!! nice help. 
and what was time taken for your TDNN-HMM  model training? on which GPU?

**Comment by bmilde** [comment]
Its about another week of training time on the GPU, after you've done the
bootstrapping. Ive trained on a titan xp.

**Comment by Tortoise17** [comment]
Thank you so much this is really really really a great help. !! Because this helps me to see if I am doing everything correct. 
I will keep you informed about my experience. and if there is anything I have to ask I will post again. Stay healthy

**Comment by Tortoise17** [comment]
thank you
