### ISSUE TITLE
Spacy v3 does not support loading from alias any more

### ISSUE THREAD

**Issue by chaosflaws** [tudarmstadt-lt/kaldi-tuda-de#55]
When trying to build the models, `run.sh` failed because of the following error message:

```
OSError: [E941] Can't find model 'de'. It looks like you're trying to load a model from a shortcut, which is obsolete as of spaCy v3.0. To load the model, use its full name instead:

nlp = spacy.load("de_core_news_sm")

```

Simply replacing the line affected in `prepare_commonvoice_data.py` seems to have fixed this.

Edit: This also applies to `renormalize_datadir_text.py`.

**Comment by Tortoise17** [comment]
You have to change the files `prepare_commonvoice_data.py , normalize_wiki_sentences.py and  renormalize_datadir_text.py `and `change spacy.load("de")` with `spacy.load("de_core_news_sm")`

**Comment by Alienmaster** [comment]
Fixed in https://github.com/uhh-lt/kaldi-tuda-de/commit/f8114ddd2c022341b40fef5f2b8e8d54e8a544a2
