### ISSUE TITLE
ERROR: FstHeader::Read: Bad FST header: standard input

### ISSUE THREAD

**Issue by bakuzen** [tudarmstadt-lt/kaldi-tuda-de#6]
I have run into the following error after running ./run.sh from scratch (i.e., I deleted all of the data and started from the beginning). Attached is the output from as far back as the console would show. For the most part, it looks like everything checks out. It even does some training for tri1, but quits after that. I know that my Kaldi version is compiled properly and working as I've used it to train other models. Any ideas?

steps/train_deltas.sh: Done training system with delta+delta-delta features in exp/tri1
fstdeterminizestar --use-log=true 
fstminimizeencoded 
fsttablecompose data/lang_test/L_disambig.fst data/lang_test/G.fst 
std::bad_allocERROR: FstHeader::Read: Bad FST header: -
ERROR (fstminimizeencoded:ReadFstKaldi():fstext/fstext-utils-inl.h:1300) Reading FST: error reading FST header from standard input
ERROR (fstminimizeencoded:ReadFstKaldi():fstext/fstext-utils-inl.h:1300) Reading FST: error reading FST header from standard input

[stack trace: ]
kaldi::KaldiGetStackTrace()
kaldi::KaldiErrorMessage::~KaldiErrorMessage()
fst::ReadFstKaldi(std::string)
fstminimizeencoded(main+0x1c0) [0x80b191b]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0xb7289a83]
fstminimizeencoded() [0x80b1681]

ERROR: FstHeader::Read: Bad FST header: standard input

[kaldierror2.txt](https://github.com/tudarmstadt-lt/kaldi-tuda-de/files/62394/kaldierror2.txt)

**Comment by svenha** [comment]
Do you have enough disk space?

**Comment by bakuzen** [comment]
Yes, I have 1.4 TB available.

**Comment by svenha** [comment]
Is openfst installed by kaldi or by you/your OS? (The first is recommended in the kaldi documentation.)

**Comment by bakuzen** [comment]
I installed it via the kaldi tools folder. I'm pretty sure Kaldi looks 
there first.

**Comment by bmilde** [comment]
Its not the disk space, but RAM: std::bad_alloc usually means that an alloc for memory failed. Try reducing the number of parallel decoding and training processes (in cmd.sh) and keep an eye out for the memory usage. I'm using the scripts on a machine with 32 Gb RAM, but if you have less you will have to reduce the number of processes from the default values.

**Comment by EchoInCloud** [comment]
7years later.. "ERROR: ... FstHeader::Read: Bad FST header: standard input" (with 128GB ram) !!!  fcKing trush app..

**Comment by bmilde** [comment]
Calling an open source project "fcKing trush" will surely help you

**Comment by EchoInCloud** [comment]
> Calling an open source project "fcKing trush" will surely help you

*Aaron Swartz*

**Comment by zhanyu1** [comment]
I also encountered some issues and requested help！
 error as follows：
Preparing train and test data
Dictionary preparation succeeded
utils/prepare_lang.sh --position-dependent-phones false data/local/dict <SIL> data/local/lang data/lang
Checking data/local/dict/silence_phones.txt ...
--> reading data/local/dict/silence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/silence_phones.txt is OK

Checking data/local/dict/optional_silence.txt ...
--> reading data/local/dict/optional_silence.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/optional_silence.txt is OK

Checking data/local/dict/nonsilence_phones.txt ...
--> reading data/local/dict/nonsilence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/nonsilence_phones.txt is OK

Checking disjoint: silence_phones.txt, nonsilence_phones.txt
--> disjoint property is OK.

Checking data/local/dict/lexicon.txt
--> reading data/local/dict/lexicon.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/lexicon.txt is OK

Checking data/local/dict/extra_questions.txt ...
--> data/local/dict/extra_questions.txt is empty (this is OK)
--> SUCCESS [validating dictionary directory data/local/dict]

**Creating data/local/dict/lexiconp.txt from data/local/dict/lexicon.txt
ERROR: FstHeader::Read: Bad FST header: standard input
Preparing language models for test
local/prepare_lm.sh: line 7: 11661 Segmentation fault      arpa2fst --disambig-symbol=#0 --read-symbol-table=$test/words.txt input/task.arpabo $test/G.fst
local/prepare_lm.sh: line 7: 11662 Segmentation fault      fstisstochastic $test/G.fst
ERROR: ReadFstClass: Can't open file: data/lang_test_tg/G.fst
ERROR: FstHeader::Read: Bad FST header: tmpdir.g/empty_words.fst
Succeeded in formatting data.
steps/make_mfcc.sh --nj 1 data/train_yesno exp/make_mfcc/train_yesno mfcc
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/train_yesno
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: Succeeded creating MFCC features for train_yesno
steps/compute_cmvn_stats.sh data/train_yesno exp/make_mfcc/train_yesno mfcc
Succeeded creating CMVN stats for train_yesno
fix_data_dir.sh: kept all 31 utterances.
fix_data_dir.sh: old files are kept in data/train_yesno/.backup
steps/make_mfcc.sh --nj 1 data/test_yesno exp/make_mfcc/test_yesno mfcc
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/test_yesno
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: It seems not all of the feature files were successfully procesed (29 != 31); consider using utils/fix_data_dir.sh data/test_yesno
steps/make_mfcc.sh: Less than 95% the features were successfully generated. Probably a serious error.
steps/compute_cmvn_stats.sh data/test_yesno exp/make_mfcc/test_yesno mfcc
Succeeded creating CMVN stats for test_yesno
fix_data_dir.sh: kept 29 utterances out of 31
fix_data_dir.sh: old files are kept in data/test_yesno/.backup
steps/train_mono.sh --nj 1 --cmd utils/run.pl --totgauss 400 data/train_yesno data/lang exp/mono0a
steps/train_mono.sh: Initializing monophone system.
bash: line 1: 12181 Segmentation fault      ( gmm-init-mono --shared-phones=data/lang/phones/sets.int "--train-feats=ark,s,cs:apply-cmvn  --utt2spk=ark:data/train_yesno/split1/1/utt2spk scp:data/train_yesno/split1/1/cmvn.scp scp:data/train_yesno/split1/1/feats.scp ark:- | add-deltas  ark:- ark:- | subset-feats --n=10 ark:- ark:-|" data/lang/topo 39 exp/mono0a/0.mdl exp/mono0a/tree ) 2>> exp/mono0a/log/init.log >> exp/mono0a/log/init.log
run.pl: job failed, log is in exp/mono0a/log/init.log
mkgraph.sh: expected data/lang_test_tg/G.fst to exist
steps/decode.sh --nj 1 --cmd utils/run.pl exp/mono0a/graph_tgpr data/test_yesno exp/mono0a/decode_test_yesno
steps/decode.sh: Error: no such file exp/mono0a/final.mdl
grep: exp/mono0a/decode_test_yesno/wer_*: No such file or directory
