### ISSUE TITLE
Number in Train set

### ISSUE THREAD

**Issue by lumaku** [tudarmstadt-lt/kaldi-tuda-de#61]
In the Tuda-De train set, there is a single sentence with a number:
```
Das Europäische Parlament konnte sein ambitioniertes Langfristziel gegenüber Rat und Kommission durchsetzen demzufolge bis zum Jahr zweitausendzwanzig der CO2 Ausstoß von Kleinsttransportern auf maximal hundertsiebenundvierzig Gramm pro gefahrenem Kilometer begrenzt wird
```
No other numbers are in the train / dev / test sets.
This should probably be replaced with its spoken equivalent, e.g. "C O zwei"...

**Comment by Alienmaster** [comment]
Hi,
i have also seen this in the dataset independently of your message and fixed it for the upcoming v4 release.  Thanks for your hint!
See: https://github.com/Alienmaster/TudaDataset/blob/master/SentencesAndIDs.cleaned.txt#L454

I created a Repository for the Tuda-DE Dataset: https://github.com/Alienmaster/TudaDataset

I let this issue open till the final release of the v4 dataset.

**Comment by bmilde** [comment]
v4 is released! See https://ltdata1.informatik.uni-hamburg.de/kaldi_tuda_de/
