### ISSUE TITLE
Additional German speech training data

### ISSUE THREAD

**Issue by lumaku** [tudarmstadt-lt/kaldi-tuda-de#62]
Hey,
I'd like to bring to your attention the German corpus from our paper "CTC-Segmentation of Large Corpora for German End-to-end Speech Recognition". It consists of audiobooks from Librivox and a re-aligned spoken wikipedia corpus.
Sources and data an be found here:
https://github.com/lumaku/german-corpus-aligned

Tuda-DE and this dataset have a certain overlap.
Both contain the SWC. M-ailabs also contains a audiobooks from librivox.
Feel free to merge etc.!

**Comment by bmilde** [comment]
We have now added Common Voice V8, bringing the total training data to a little over 1700 hours. We have a new WER record with the most recent model as well: 6.19% WER on Tuda Dev and 6.93% WER on Tuda Test :)
