### ISSUE TITLE
Common Voice 7.0?

### ISSUE THREAD

**Issue by ErnstTmp** [tudarmstadt-lt/kaldi-tuda-de#63]
Hello! 
I would like to train your tuda-de model with the current common voice dataset 7.0 with 965 hrs of German text. Can I bring it in the kaldi formats (scp,...), split it in train, test, dev and add it to the corresponding files, or did you do some cleansing / preprocessing?

Thanks for your feedback and kind regards,
Ernst

**Comment by bmilde** [comment]
Hi Ernst,

the script to import this data (
https://github.com/uhh-lt/kaldi-tuda-de/blob/master/s5_r2/local/prepare_commonvoice_data.py)
should also work with the newer version, if the format didn't change. Note
that we have so far only included the train dataset of commonvoice and
tested on tuda (dev/test). There's probably also an official dev/test from
commonvoice now. It would certainly be interesting to see what the numbers
are on that as well.

We are also working on including this new data and will probably have pre
trained models as well in a few months,

Best,
Benjamin




Am Do., 9. Dez. 2021 um 09:58 Uhr schrieb ErnstTmp ***@***.***

**Comment by bmilde** [comment]
We have a new branch for kaldi-tuda-de to include the newest Common Voice dataset: https://github.com/uhh-lt/kaldi-tuda-de/tree/CV7

Despite the name CV7 we already upgraded this branch to version 8. Currently you need to get your own cleaned LM text data to train this (see https://github.com/bmilde/german-asr-lm-tools).

We should soon release new pre trained models, training takes a while as there is a lot of new data in the newest CV release. Total is about 1700h now.

**Comment by bmilde** [comment]
closing this, since we now merged the new recipe with Common Voice V8
