### ISSUE TITLE
missing dictionary files

### ISSUE THREAD

**Issue by jaktk** [tudarmstadt-lt/kaldi-tuda-de#68]
There seem to be missing information in `data/local/dict`. Could you please provide the following files:
- `silence_phones.txt`
- `nonsilence_phones.txt`
- `optional_silence.txt`

I might have missed them somewhere but I don't think so.

**Comment by bmilde** [comment]
Hi, these files are auto generated by the prepare scripts (https://github.com/uhh-lt/kaldi-tuda-de/blob/master/s5_r2/local/build_big_lexicon.py). My guess is something went wrong and they failed, so you need to watch the output of stages 2,3 and 4 carefully.
