### ISSUE TITLE
Wrong timeout data type?

### ISSUE THREAD

**Issue by cknothe** [tudarmstadt-lt/kaldi-tuda-de#9]
Tried several times to get this to run. Followed the steps within the README.md , but every time all training data is dropped because either it is not complete or an error like this happens:

. Error in file, omitting data/wav/german-speechdata-package-v2/dev/2015-01-27-11-31-32
Timeout value connect was (10.0, 10.0), but it must be an int or float.

Tried with Xubuntu 14.04.

The rest of the output(omitted thousands of similar messages at [...]):
[outs_low_redundancy.txt](https://github.com/tudarmstadt-lt/kaldi-tuda-de/files/377871/outs_low_redundancy.txt)

EDIT:
Changed local/maryclient.py line 63 from:
        r = self.connection_pool[connection_pool_num].post('http://'+self.host+':'+str(self.port)+'/process',data=params,timeout=(10.0, 10.0))
to:
        r = self.connection_pool[connection_pool_num].post('http://'+self.host+':'+str(self.port)+'/process',data=params,timeout=10.0)

**Comment by svenha** [comment]
Does your change behind "EDIT:" solve the issue?
